spring.application.name=backend
server.port=8080

# Scheduled Tasks (pour nettoyer les tokens expirés)
spring.task.scheduling.pool.size=2
spring.data.mongodb.uri=mongodb://localhost:27017/event_db
spring.data.mongodb.database=event_db

spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
# 24 heures en millisecondes

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evenementiel.app@gmail.com
spring.mail.password=hqlq oejo dyvw vebf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Frontend URL
app.frontend.url=http://localhost:4200

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.dic1.projet.trans.backend=DEBUG

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:4200

# Twilio Configuration
twilio.account.sid=ACde8bec5be2bb698557692b96c7732a85
twilio.auth.token=f2421e15aa378758483984509dd99e6e
twilio.phone.number=+18646644724

